/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 18, 2010, 5:12:49 PM
 */

package com.cn.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.HashMap;

import com.cn.constants.ProtocolConstants;
import com.cn.protocol.Protocol;


/**
 *
 * @author Michael
 */
@SuppressWarnings("serial")
public class SelectCharacter extends javax.swing.JFrame {


	/** Creates new form NewJFrame */
	public SelectCharacter() {
		this.setVisible(true);
	}

	String char1Stats = "";
	String char2Stats = "";
	String char3Stats = "";
	String char4Stats = "";

	public SelectCharacter(String getStatsResponse) {
		System.out.println("Inside SelectCharacter constructor with response");
		initComponents();
		initIconImage();
		this.setVisible(true);

		int subst_length = ProtocolConstants.SUCCESS.length() + ProtocolConstants.CHARACTER.length();
		String[] charArray = getStatsResponse.substring(subst_length).split(ProtocolConstants.CHARACTER);
		HashMap<String, String[]> charMap = new HashMap<String, String[]>();
		for(String character : charArray) {
			String name = Protocol.getRequestCmdSimple(character);
			String[] stats = Protocol.getRequestArgsSimple(character);
			charMap.put(name, stats);
		}
		addTextToButtons(charMap);
		initBackgroundImage();
	}




	private void addTextToButtons(HashMap<String, String[]> charMap) {
		String[] charNames = new String[4];
		String[][] charStats = new String[4][6];
		int i = 0;
		for(String name : charMap.keySet()) {
			charNames[i] = name;
			charStats[i] = charMap.get(name);
			i++;
		}

		char1Stats = parseStats(charStats[0]);
		char2Stats = parseStats(charStats[1]);
		char3Stats = parseStats(charStats[2]);
		char4Stats = parseStats(charStats[3]);

		charButton1.setText(charNames[0]);
		charButton2.setText(charNames[1]);
		charButton3.setText(charNames[2]);
		charButton4.setText(charNames[3]);
	}

	private String parseStats(String[] statsArray) {
		//lvl, health, energy, xp, credits
		String newline = "\n";
		String stats = "Selected Character:" + newline;
		stats += "Name: " + statsArray[0] + newline;
		stats += "Level: " + statsArray[1] + newline;
		stats += "XP: " + statsArray[2] + newline;
		stats += "Health: " + statsArray[3] + newline;
		stats += "Energy: " + statsArray[4] + newline;
		stats += "Credits: " + statsArray[5] + newline;
		return stats;
	}

	private void initIconImage() {
		Image img = Toolkit.getDefaultToolkit().getImage("src/images/projectedwater3.jpg");
		this.setIconImage(img);
	}
	
	private void initBackgroundImage() {
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setIcon(new javax.swing.ImageIcon("src/images/projectedwater3.jpg"));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, this.getWidth(), this.getHeight());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	public void initComponents() {

		jButton1 = new javax.swing.JButton();
		charButton2 = new javax.swing.JButton();
		charStatsTextArea = new javax.swing.JTextArea();
		charButton4 = new javax.swing.JButton();
		charButton3 = new javax.swing.JButton();
		charButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		//setBackground(new java.awt.Color(0, 0, 0));
		//setForeground(new java.awt.Color(0, 0, 0));
		setResizable(false);

		jButton1.setText("Play");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				clickedPlayButton(evt);
			}
		});

		charButton2.setText("2");
		charButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				clickedCharButton2(evt);
			}
		});

		charStatsTextArea.setBackground(new java.awt.Color(240, 240, 240));
		charStatsTextArea.setText("Select a character!");
		charStatsTextArea.setBorder(null);


		charButton4.setText("4");
		charButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				clickedCharButton4(evt);
			}
		});

		charButton3.setText("3");
		charButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				clickedCharButton3(evt);
			}
		});

		charButton1.setText("1");
		charButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				clickedCharButton1(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(98, 98, 98)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(charButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(charButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
								.addComponent(charStatsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(64, 64, 64)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(charButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(charButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(74, 74, 74))
										.addGroup(layout.createSequentialGroup()
												.addGap(353, 353, 353)
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(372, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(119, Short.MAX_VALUE)
						.addComponent(charStatsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(155, 155, 155)
						.addComponent(jButton1)
						.addGap(37, 37, 37))
						.addGroup(layout.createSequentialGroup()
								.addGap(54, 54, 54)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(charButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(charButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(120, 120, 120)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(charButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(charButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(139, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>


	private void clickedPlayButton(java.awt.event.MouseEvent evt) {                                   
		String text = charStatsTextArea.getText();
		charStatsTextArea.setText(text + " was selected.");
	}                                  

	private void clickedCharButton1(java.awt.event.MouseEvent evt) {                                
		// TODO add your handling code here:
		charStatsTextArea.setText(char1Stats);
	}                               

	private void clickedCharButton2(java.awt.event.MouseEvent evt) {
		charStatsTextArea.setText(char2Stats);
	}

	private void clickedCharButton3(java.awt.event.MouseEvent evt) {
		charStatsTextArea.setText(char3Stats);
	}

	private void clickedCharButton4(java.awt.event.MouseEvent evt) {
		charStatsTextArea.setText(char4Stats);
	}  

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SelectCharacter().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton charButton1;
	private javax.swing.JButton charButton2;
	private javax.swing.JButton charButton3;
	private javax.swing.JButton charButton4;
	private javax.swing.JButton jButton1;
	private javax.swing.JTextArea charStatsTextArea;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration

}
