/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 18, 2010, 5:12:49 PM
 */

package com.cn.gui;

/**
 *
 * @author Michael
 */
@SuppressWarnings("serial")
public class SelectCharacter extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public SelectCharacter() {
        initComponents();
        this.setVisible(true);
    }
    
    String char1Stats = "";
    String char2Stats = "";
    String char3Stats = "";
    String char4Stats = "";

    public SelectCharacter(String charName1, String charName2, String charName3,
    		String charName4) {
    	System.out.println("Inside SelectCharacter constructor with 4 char names.");
    	System.out.println(charName1 + ", " + charName2 + ", " + charName3 + ", " + charName4);
    	initComponents();
        this.setVisible(true);
        setButtonText(charName1, charName2, charName3, charName4);
    }

    private void setButtonText(String charName1, String charName2,
    		String charName3, String charName4) {
    	charButton1.setText(charName1);
    	char1Stats = "";
    	charButton2.setText(charName2);
    	char2Stats = "";
    	charButton3.setText(charName3);
    	char3Stats = "";
    	charButton4.setText(charName4);
    	char4Stats = "";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        charButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        charButton4 = new javax.swing.JButton();
        charButton3 = new javax.swing.JButton();
        charButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Play");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedPlayButton(evt);
            }
        });

        charButton2.setText("2");
        charButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedCharButton2(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("stats will show up here");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        charButton4.setText("4");
        charButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	clickedCharButton4(evt);
            }
        });

        charButton3.setText("3");
        charButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	clickedCharButton3(evt);
            }
        });

        charButton1.setText("1");
        charButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	clickedCharButton1(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(charButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(charButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void clickedPlayButton(java.awt.event.MouseEvent evt) {                                   
       String text = jTextField1.getText();
       jTextField1.setText(text + " was selected.");
    }                                  

    private void clickedCharButton1(java.awt.event.MouseEvent evt) {                                
        // TODO add your handling code here:
    	jTextField1.setText(char1Stats);
    }                               

    private void clickedCharButton2(java.awt.event.MouseEvent evt) {
    	jTextField1.setText(char2Stats);
    }

    private void clickedCharButton3(java.awt.event.MouseEvent evt) {
    	jTextField1.setText(char3Stats);
    }

    private void clickedCharButton4(java.awt.event.MouseEvent evt) {
    	jTextField1.setText(char4Stats);
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	//TODO: do stuff.
    }    

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton charButton1;
    private javax.swing.JButton charButton2;
    private javax.swing.JButton charButton3;
    private javax.swing.JButton charButton4;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration

}
